### ISSUE TITLE
Port the original Http.url API to this project.

### ISSUE THREAD

**Issue by lijunle** [elm/http#10]
Hi, could you please port the original [Http.url](https://github.com/evancz/elm-http/blob/3.0.1/src/Http.elm#L57) API to here?

I am using the following code as a workaround:

```elm

url : String -> List ( String, String ) -> String
url baseUrl query =
    case query of
        [] ->
            baseUrl

        _ ->
            let
                queryPairs =
                    query |> List.map (\( key, value ) -> Http.encodeUri key ++ "=" ++ Http.encodeUri value)

                queryString =
                    queryPairs |> String.join "&"
            in
                baseUrl ++ "?" ++ queryString
```

**Comment by evancz** [comment]
These kinds of needs should be covered by [`elm/url`](https://package.elm-lang.org/packages/elm/url/latest) now.  Functions like [`Url.Builder.absolute`](https://package.elm-lang.org/packages/elm/url/latest/Url-Builder#absolute) and [`Url.Builder.relative`](https://package.elm-lang.org/packages/elm/url/latest/Url-Builder#relative) give a bit more control even.
