### ISSUE TITLE
No longer possible to tunnel binary data as text

### ISSUE THREAD

**Issue by newlandsvalley** [elm/http#11]
With evancz/elm-http I was able to access binary data without it being mangled by means of the overrideMimeType hack  - SSCCE [here](https://gist.github.com/newlandsvalley/9cb76e88d2b2c6108b3338fffd9e39dd).  I no longer seem to be able to do this in elm 0.18 - failing SSCCE [here](https://gist.github.com/newlandsvalley/945d278e0570254285f77d0e863e8059). In each case I am trying to load [this](https://github.com/newlandsvalley/elm-comidi/blob/master/test/midi/chordsample.midi) small MIDI file, served up with Apache.  I am using 64-bit Linux and the latest Chromium browser.

These two examples give different results when displaying the (decoded) data.  They differ at the first truly binary value which is greater than FF  (in this example, byte 23).

In particular, this line of javascript has now vanished in the implementation of http:

    // ask for a specific MIME type for the response
		if (settings.desiredResponseType.ctor === 'Just')
		{
			req.overrideMimeType(settings.desiredResponseType._0);
		}

**Comment by evancz** [comment]
There is explicit support for binary data in version 2.0.0 of this package.
