### ISSUE TITLE
Document withCredentials

### ISSUE THREAD

**Issue by DavidDTA** [elm/http#19]
`request` takes a record containing `withCredentials`, but the documentation does not give any indication as to what a value of `True` or `False` means.

**Comment by newmana** [comment]
I assume it means:
"The XMLHttpRequest.withCredentials property is a Boolean that indicates whether or not cross-site Access-Control requests should be made using credentials such as cookies, authorization headers or TLS client certificates. Setting withCredentials has no effect on same-site requests."

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

**Comment by asonix** [comment]
Hey, this has been open for over a year with no explanation

**Comment by evancz** [comment]
This ability is now available through the `riskyRequest` function, and it is documented more clearly now: https://package.elm-lang.org/packages/elm/http/latest/Http#riskyRequest
