### ISSUE TITLE
Progress has no Native.Http import

### ISSUE THREAD

**Issue by tunguski** [elm/http#30]
`Progress` is the only module (in core and http) that uses native module without explicitly importing it: https://github.com/elm-lang/http/blob/99c00a2dac21dda1d4954515c79e6f28e431573f/src/Http/Progress.elm#L164. I'm not sure does it break language specification or not. Still it creates an exception.

Simple fix would be to add import.

**Comment by evancz** [comment]
With the changes in 0.19 this should be resolved. If you are still seeing problems, share an SSCCE that triggers the error you are seeing!
