### ISSUE TITLE
Feature request: Type alias for the argument to Http.request

### ISSUE THREAD

**Issue by JordyMoos** [elm/http#38]
Can we have a type alias for the argument going to Http.request?

Current:
```elm
request : { method : String, headers : List Header, url : String, body : Body, expect : Expect a, timeout : Maybe Time, withCredentials : Bool } -> Request a
```

Requested:
```elm
-- Sugestions for better namings are welcome
type alias Configuration =
    { method : String
    , headers : List Header
    , url : String
    , body : Body
    , expect : Expect a
    , timeout : Maybe Time
    , withCredentials : Bool
    }

request : Configuration -> Request a
```

Because now i have two choices:

1. Put the whole record in all the functions that want to receive and return that record.

2. Make an alias myself. But the issue is that i have one request handlers that use that. And also multiple interceptors that use that record. Creating the alias in the handler gives me circular dependencies. So the only option is to move the type alias into an other file where they both depend on.

I think it does make sense to create the alias in this package

**Comment by evancz** [comment]
I don't think adding this type would detract from the clarity of the API because now to understand `Http.request` you have to start jumping around. So I get that it'd be convenient once you already know things, but the other concern is a bigger design goal.

**Comment by JordyMoos** [comment]
Ok, thanks for answering the issue
