### ISSUE TITLE
Http.Progress not working when the content is gzipped

### ISSUE THREAD

**Issue by pablohirafuji** [elm/http#42]
If the content is not gzipped, the progress bar seems to work fine on all the browsers I have tested so far. But if the server sends it as gzip, only Firefox works[¹].

This appears to be a [XHR spec issue](https://bugs.chromium.org/p/chromium/issues/detail?id=463622), for what I understood, chrome and others browsers does not implement tracking progress when the content is gzipped because the specs are unclear whether the value of the `content-length` header should be after-decoding or before-decoding.

Tests can be done in this link: https://pablohirafuji.github.io/elm-http-progress-example/

[¹]: https://stackoverflow.com/questions/35985418/xmlhttprequest-progress-event-issue-with-gzipped-content-except-firefox

**Comment by evancz** [comment]
Is there any proposal of concrete changes that should be made to how this library works as a result of this underlying disagreement?

**Comment by pablohirafuji** [comment]
With the new `elm/http` and `elm/file` packages, there is not. I really like the new http api and the `elm/file` and `elm/bytes` packages. Just using your packages makes me a better programmer, gives me a better discernment of good and bad mental models. Yours being the standard for good, of course. I do not objectively know why, but it makes me do  simpler, debuggable, coherent, non contraditory, reasonable and enjoyful codes.
Thank you for being who you are!
