### ISSUE TITLE
Handling custom errors in 2.0.0

### ISSUE THREAD

**Issue by nabilspottt** [elm/http#51]
Hello there,

At my job, we are experiencing some difficulties switching to v2.0.0 as we are trying to provide our requests   different _return messages_ according to the http status of the response. Because now the Http.Error BadStatus only provides the http code, we cannot get further data from the response. We are trying to _pattern-match_ the http status and catch the response directly with the function expectStringResponse but it seems a bit complicated.

So why not directly exposing  the response through BadStatus anymore ?
And do some of you have examples of how to easily handle custom errors through the new API ?

Thanks for reading, please forgive my english :)

**Comment by evancz** [comment]
I think the [`expectStringResponse`](https://package.elm-lang.org/packages/elm/http/latest/Http#expectStringResponse) function will help you.

It gives you full access to the [`Response`](https://package.elm-lang.org/packages/elm/http/latest/Http#Response) and [`Metadata`](https://package.elm-lang.org/packages/elm/http/latest/Http#Metadata), so you can do whatever you want with it.

For further questions, I recommend asking on https://discourse.elm-lang.org/ or https://elmlang.herokuapp.com/ where there are a bunch more folks who would have an easier time replying!

**Comment by sporto** [comment]
We have the same issue.

In v2 error information was removed from `BadStatus`. Having a status only is not enough for logging and auditing error. For example it is usual to return 422 errors when you receive a bad input from the front end, with details about the error in the body.

Please consider adding this information back to `Error`.

Also some libraries like `elm-graphql` wrap `Error`. They have lost valuable error information in the upgrade.
