### ISSUE TITLE
Methods for building PUT and DELETE requests?

### ISSUE THREAD

**Issue by dimbleby** [elm/http#9]
We have `Http.get` and `Http.post`.  Can we have `Http.delete` and `Http.put` as well?  

I'd contend that these are common enough on REST APIs that these methods are worth their place though of course it's true that I can always fall back to `Http.request`.

Happy to send a pull request, if you're open to this.

**Comment by evancz** [comment]
The API of [`request`](https://package.elm-lang.org/packages/elm/http/latest/Http#request) is:

```elm
request :
    { method : String
    , headers : List Header
    , url : String
    , body : Body
    , expect : Expect msg
    , timeout : Maybe Float
    , tracker : Maybe String
    }
    -> Cmd msg
```

So maybe we could save one line of `method = "PUT"` but I don't really see which other fields should definitely be left out. Maybe you don't need one of them, but I bet another person does. So in the end, I don't think adding something here will make things easier overall.

**Comment by dimbleby** [comment]
Shall we remove `Http.get` and `Http.post` for the same reasons then?
